services:
  backend:
    container_name: weeks_backend
    build:
      context: ./weeks-backend
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8201:3333"
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=
      - DRIVE_DISK=local
      - DB_CONNECTION=pg
      - PG_HOST=localhost
      - PG_PORT=5432
      - PG_USER=
      - PG_PASSWORD=
      - PG_DB_NAME=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
  frontend:
    container_name: weeks_frontend
    build:
      context: ./weeks-frontend
      dockerfile: Dockerfile
    ports:
      - "8102:3000"
    environment:
      - VITE_API_URL="http://localhost:3333/"